---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-dashboard-cluster-manager
subjects:
- kind: ServiceAccount
  name: chaos-dashboard
  namespace: chaos-mesh
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dashboard-httproute
  namespace: chaos-mesh
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    port: 8000
  hostnames:
  #TODO: change to TRAEFIK IP address
  - chaos-104.248.98.110.nip.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: chaos-dashboard
      namespace: chaos-mesh
      port: 2333

