---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: books-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-role
rules:
  # k8s_leader_elector
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# kubeletstats + k8s_cluster
- apiGroups: [""]
  resources: ["nodes", "nodes/stats", "nodes/proxy"]
  verbs: ["get", "list", "watch"]

# k8sattributes + k8s_cluster
- apiGroups: [""]
  resources: ["pods", "namespaces", "endpoints", "services",
              "replicationcontrollers", "resourcequotas"]
  verbs: ["get", "list", "watch"]

# k8sattributes + k8s_cluster
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]

- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses" ]
  verbs: ["get", "list", "watch"]

- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-role
subjects:
- kind: ServiceAccount
  name: otel-collector-sa
  namespace: books-ns

