---
apiVersion: v1
kind: Namespace
metadata:
  name: books-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-cm
  namespace: books-ns
data:
  # books-server
  BOOKS_SERVER_PORT: '5000'
  # TODO: Task 4 - deployed otel host 
  OTEL_COLLECTOR_HOST: __GATEWAY_COLLECTOR_HERE__
  ERROR_INJECTION_RATE: '15'
  DB_ERROR_INJECTION_RATE: '10'

  # books-frontend
  BOOKS_FRONTEND_PORT: '8080'
  BOOKS_SERVER: booksserver-svc.books-ns.svc.cluster.local
  CADDY_LOG: /var/log/caddy
  OTEL_SERVICE_NAME: caddy-server
  # TODO: Task 4 - deployed otel host 
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: __GATEWAY_COLLECTOR_HERE__
  OTEL_RESOURCE_ATTRIBUTES: service.version=1.0
  LOG_LEVEL: DEBUG

---
apiVersion: v1
kind: Secret
metadata:
  name: books-secret
  namespace: books-ns
type: Opaque
stringData:
  # books-server
  BOOKS_URL: mysql://root:changeit@booksdb-svc.books-ns.svc.cluster.local:3306/acme_books
  # MySQL exporter
  MYSQLD_EXPORTER_PASSWORD: changeit

