---
apiVersion: v1
kind: ConfigMap
metadata:
  name: booksfrontend-cm
  namespace: books-ns
data:
  Caddyfile: |

    :{$PORT:8080} {

      log {
        output file {$CADDY_LOG:/var/log}/caddy.log {
          roll_size 50MiB
          roll_keep 5
        }
        format json
        level {$LOG_LEVEL:INFO}
      }

      root * ./html

      handle /api/* {
        reverse_proxy {$BOOKS_SERVER:localhost}:{$BOOKS_SERVER_PORT:5000}
      }

      handle {
        try_files {path} {path}/index.html =404
        file_server
      }

      handle_errors {
        rewrite * /error.html
        templates
        file_server
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: booksfrontend-hsvc
  namespace: books-ns
spec:
  clusterIP: None
  selector:
    app: books
    component: booksfrontend
  ports:
  - name: booksfrontend
    port: 8080
    targetPort: booksfrontend

---
apiVersion: v1
kind: Service
metadata:
  name: booksfrontend-svc
  namespace: books-ns
spec:
  type: ClusterIP
  selector:
    app: books
    component: booksfrontend
  ports:
  - name: booksfrontend
    port: 8080
    targetPort: booksfrontend

---
# https://opentelemetry.io/docs/platforms/kubernetes/operator/automatic/
# https://opentelemetry.io/docs/platforms/kubernetes/operator/automatic/#opt-in-a-go-service
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booksfrontend-sts
  namespace: books-ns
spec:
  replicas: 1
  serviceName: booksserver-hsvc
  selector:
    matchLabels:
      app: books
      component: booksfrontend
  volumeClaimTemplates:
  - apiVersion: v1 
    kind: PersistentVolumeClaim
    metadata:
      name: caddy-vol
    spec:
      accessModes: [ ReadWriteOncePod ]
      # TODO: Task 4 - Change this to an appropriate storageClassName
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: books
        component: booksfrontend
        app.kubernetes.io/name: booksfrontend
        app.kubernetes.io/version: "1.7"
      annotations:
        instrumentation.opentelemetry.io/inject-go: books-ns/gateway-otelinst
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: /usr/bin/caddy
    spec:
      volumes:
      - name: caddyfile
        configMap:
          name: booksfrontend-cm
      containers:
      - name: booksfrontend-container
        image: chukmunnlee/books-frontend:v2.3-debug-amd64
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: caddy-vol
          mountPath: /var/log/caddy
        - name: caddyfile
          mountPath: /www/Caddyfile
          subPath: Caddyfile
          readOnly: true
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: books-cm
              key: BOOKS_FRONTEND_PORT
        envFrom:
        - configMapRef:
            name: books-cm
        - secretRef:
            name: books-secret
        ports:
        - name: booksfrontend 
          containerPort: 8080

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: booksfrontend-httproute
  namespace: books-ns
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    port: 8000
  hostnames:
  #TODO: Task 4 - change the TRAEFIK_IP to the load balancer IP address
  - books-104.248.98.110.nip.io

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: booksfrontend-svc
      namespace: books-ns
      port: 8080
