---
apiVersion: chaos-mesh.org/v1aplha1
kind: PodChaos
metadata:
  name: recommendation-pod-kill
  namespace: quickpizza
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - quickpizza
    labelSelectors:
      app.k8s.io/name: quickpizza
      app.kubernetes.io/component: service
      app.kubernetes.io/instance: recommendations
  gracePeriod: 0
  duration: 3m
