---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: quickpizza-instrument
  namespace: quickpizza
spec:
  defaults:
    # pick specifc labels from pods and add them as metric labels
    useLabelsForResourceAttributes: true
  exporter:
      endpoint: http://quickpizza-gateway-collector.quickpizza.svc.cluster.local:4318

  propagators:
  - tracecontext
  - baggage
  - jaeger
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
