# https://github.com/grafana/tempo/blob/main/example/docker-compose/local/tempo.yaml
stream_over_http_enabled: true
# run all componets in a single binary
target: all

# Global configuration
overrides:
  metrics_generator_processors: [local-blocks, service-graphs, span-metrics]

server:
  http_listen_port: 3200
  log_level: info
  log_format: logfmt

distributor:
  receivers: 
    otlp:
      protocols:
        grpc: 
          endpoint: 0.0.0.0:4317
        http: 
          endpoint: 0.0.0.0:4318

storage:
  trace:
    backend: local                
    local:
      path: /var/tempo/traces      # Set to correct path on your computer
    wal:
      path: /var/tempo/wal         # Set to correct path on your computer

# https://grafana.com/docs/tempo/latest/configuration/#compactor
#compactor:
#  compaction:
#    compacted_block_retention: 2h
#    compaction_window: 1h
#    max_compaction_objects: 1000
#    block_retention: 24h

# https://grafana.com/docs/tempo/latest/configuration/#ingester
ingester:
  max_block_duration: 5m


# https://grafana.com/docs/tempo/latest/operations/traceql-metrics/
metrics_generator:
  processor:
    span_metrics: 
      enable_target_info: true
    local_blocks:
      flush_to_storage: true
      filter_server_spans: false
  traces_storage:
    path: /var/tempo/generator/traces
  storage:
    path: /var/tempo/generator/wal
    # Enable service graph
    remote_write:
    - url: http://prometheus:9090/api/v1/write

# https://grafana.com/docs/tempo/latest/configuration/#querier
# https://grafana.com/docs/tempo/latest/operations/backend_search/
querier:
  max_concurrent_queries: 20
  trace_by_id:
    query_timeout: 30s

query_frontend:
  max_retries: 3
